### ISSUE TITLE
Change saves location

### ISSUE THREAD

**Issue by XargonWan** [bardeci/dot-matrix-simulator#12]
Is it possible to make gambatte saving into a save folder instead of inside the roms folder?

Why?
More details here: https://github.com/XargonWan/RG-350-M-Unified-Save-folder

**Comment by bardeci** [comment]
gambatte.opk is a very old and outdated port from like 2015. It's based on an older version of gambatte and lacks pretty much every single extra feature i've introduced. I dont even know why the anbernic guys are packing that one with the firmware, as it's creating confusion among the users and gambatte emulates both GB and GBC (since always).
My advice (to everyone) is to delete it and use the latest gambatte-dms (from this repo) for both GB and GBC.

**Comment by bardeci** [comment]
Since people "need" to have separate GB and GBC icons in their menu, i'll make it so 2 separate links (with GB and GBC icons) are shown on the next release of gambatte-dms. (single OPK, two different links on the menu).
Keep in mind that you DONT need two separate emulators for GB and GBC, and having 2 links doesn't always mean you're using 2 separate emulators.

**Comment by XargonWan** [comment]
Yeah, that was my follow-up question. thanks for the reply :)
