### ISSUE TITLE
Bootlegs on Gambatte

### ISSUE THREAD

**Issue by MassiveBox** [bardeci/dot-matrix-simulator#23]
Hello, I've been enjoying playing GBC and GB roms on Gambatte on RS97 for a while now, but I found a problem: it won't recognize the GB rom of "[Sonic 3D Blast 5](http://info.sonicretro.org/Sonic_3D_Blast_5)" (download at end of page). I've tried with its GBC sequels, "Sonic Adventure 7" and 8, and they both work without any problem.  
The error I get is this: "bad file or unknown MBC" (gotten via the gmenu logger thing).

I should add that this game works with the RetroArch GB "accurate" core (https://github.com/Poligraf/retroarch_cores_retrofw/blob/main/gameboy_(accurate)_gearboy_libretro.so) but does not boot with the "fast" one (https://github.com/Poligraf/retroarch_cores_retrofw/blob/main/gameboy_(fast)_gambatte_libretro.so)

Feel free to ask if I need to clarify anything.  
Thank you a lot for your great work on this emulator.

**Comment by bardeci** [comment]
I see it works with gearboy (libretro "accurate" core), which is a different emulator than gambatte (libretro "fast" core).
Those are entirely different emulators, so i cannot just "update" the core.

However, i could add an option for the emulator to ignore MBC errors, so in case the emulator detects an unknown or unsupported MBC, the emulator would just try to load the game normally instead of throwing an error and refusing to load the ROM.
Of course, keep in mind that there is no guarantee that the game would work properly. But at least, the emulator will try.

I will do some tests and will let you know.

Greetings!

**Comment by bardeci** [comment]
I took a look at what gearboy was doing, and it's just loading Sonic 3D Blast 5 as MBC1. I modified gambatte so it does the same, and it works.

**Comment by bardeci** [comment]
Just released a new update. Enjoy!
https://github.com/bardeci/gambatte-dms/releases/latest
