### ISSUE TITLE
Filters option in video settings dissappeard

### ISSUE THREAD

**Issue by malaccio** [bardeci/dot-matrix-simulator#6]
I can't set filter in the last version. Did you remove this option?

**Comment by bardeci** [comment]
Nope, not removed. But the option is not available when you are playing a DMG game (filter option is for GBC only, mono palette option is for DMG only).

The same way, if you're playing in GBC mode, the filter option is available but the mono palette option is not available.

**Comment by bardeci** [comment]
I did that to clean up the menu and to make it more intuitive, because if you tried to change the filter settings while playing a DMG game you will not see anything (obviously). The DMG/GBC border options work in the same way. It makes no sense to have a GBC border option when you're playing a DMG game because when you change it you wont see any effect.

So that way only the relevant options are available at any moment.

**Comment by malaccio** [comment]
ok cool !

**Comment by bardeci** [comment]
I'll mark this as closed.
