### ISSUE TITLE
Add note to the documentation/instructions regarding mapping the controls so that B=A and Y=B.

### ISSUE THREAD

**Issue by nl255** [bardeci/dot-matrix-simulator#8]
Please consider adding an option to the controller mapping settings so that the B and Y buttons are mapped to A and B.

**Comment by bardeci** [comment]
I think there is already such a mapping option. It's called "Alternate".
Try it and tell me what you think.

**Comment by nl255** [comment]
I am pretty sure alternate just swaps the A and B buttons.

**Comment by bardeci** [comment]
I'd encourage you to try again: Menu > Settings > Controls > Button Layout > Alternate.
It swaps all ABXY button mappings from B to A and from A to B, so you go from a BAAB button layout to an ABBA layout, which is what you're looking for.

I know it works like that because i coded it myself.

**Comment by nl255** [comment]
I just tested it and it looks like normal is like that while alternate is the way you describe normal, at least on the pocketgo.  I was just going by what all the instructions seemed to say which was that it was either A=A/B=B or A=B and B=A.

**Comment by bardeci** [comment]
Oh, you're using the pocketgo!
Yes, the pocketgo and bittboy have their button mappings swapped (if we compare them with the standard used by every other open handheld). It is a firmware issue which no one cared to fix (and i guess no one will).

That's why i introduced the "alternate" option, so the users of those consoles could simply select the alternate mapping and have the buttons properly mapped.

**Comment by merwok** [comment]
Could there be a note in the readme to explain the meaning of alternate and alternate 2?
(and also mention which key is the fast-forward hotkey)

thanks!
